_LABEL_FILE = '/BiG_DRP_data//drp-data/grl-preprocessed/drug_response/BiG_DRP_tuple_labels_folds.csv'
_GENE_EXPRESSION_FILE = '/BiG_DRP_data//drp-data/grl-preprocessed/sanger_tcga//BiG_DRP_fpkm.csv'
_LABEL_MATRIX_FILE = '/BiG_DRP_data//drp-data/grl-preprocessed/drug_response/BiG_DRP_data_cleaned.csv'
_DRUG_DESCRIPTOR_FILE = '/BiG_DRP_data//drp-data/grl-preprocessed/drug_features//BiG_DRP_descriptors.csv'
_MORGAN_FP_FILE = '/BiG_DRP_data//drp-data/grl-preprocessed/drug_features//BiG_DRP_morgan.csv'
